# actions/release-gate-action/action.yml

name: 'ArmorCode Release Gate Action'
description: 'Validates ArmorCode release gate inputs and echoes them for now.'

inputs:
  product:
    description: 'Product name'
    required: true
  subProduct:
    description: 'Subproduct name'
    required: true
  environment:
    description: 'Environment'
    required: true
  mode:
    description: 'Mode (warn or block)'
    required: true
  aql:
    description: 'AQL filter (e.g., scanType=SAST)'
    required: false
  armorcode_token:
    description: 'ArmorCode API token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo Release Gate Inputs
      shell: bash
      run: |
        echo "🔐 ArmorCode Release Gate Triggered"
        echo "----------------------------------"
        echo "Product       : ${{ inputs.product }}"
        echo "SubProduct    : ${{ inputs.subProduct }}"
        echo "Environment   : ${{ inputs.environment }}"
        echo "Mode          : ${{ inputs.mode }}"
        echo "AQL           : ${{ inputs.aql }}"
        echo "Token Present : ${{ inputs.armorcode_token != '' }}"
