name: 'ArmorCode Release Gate'
description: 'Integrates ArmorCode release gates into your GitHub workflows to enforce security policies'
author: 'ArmorCode'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  group_name:
    description: 'ArmorCode group name'
    required: true
  sub_group_name:
    description: 'ArmorCode sub-group name'
    required: true
  environment:
    description: 'Environment (e.g., production, staging)'
    required: true
  mode:
    description: 'Mode of operation - "block" will fail the workflow, "warn" will only print warnings'
    required: true
    default: 'block'
  aql:
    description: 'Additional AQL query parameters'
    required: false
    default: ''
  armorcode_token:
    description: 'ArmorCode API token'
    required: true
  max_retries:
    description: 'Maximum number of retries for checking release gate status'
    required: false
    default: '5'
  api_url:
    description: 'ArmorCode API URL'
    required: false
    default: 'https://app.armorcode.com'

runs:
  using: 'node20'
  main: 'dist/index.js'
