# File: release-gate-action/action.yml

on: 
  workflow_call:
name: ArmorCode Release Gate Test
jobs:
  merge-release-back-to-qa:
    timeout-minutes: 2
    runs-on: ubuntu-latest

runs:
  using: "composite"
  steps:
    - run: |
        echo "=== ArmorCode Release Gate Inputs ==="
        echo "Product       
        echo "SubProduct   
        echo "Environment  
        echo "Mode         
        echo "AQL           
      shell: bash
